name: Bot workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Please wait...
      run: |
        sudo apt install libffi-dev python3-pip python3-setuptools python3-dev libssl-dev build-essential libyaml-dev lib32ncurses5-dev libsnappy-dev -y
        git clone https://github.com/N3RDP0RT4L-HQ/GoddessBlackHeartBot
        cd GoddessBlackHeartBot
        wget ${{ secrets.config }} -o config.json
        pip3 install python-snappy --user
        echo next
        pip3 install multidict lavalink aiohttp asyncpg requests discord discord.py dataIO clint config timestring loadconfig yarl lxml --user
        #pip3 install -r requirements2.txt --user
        python3 GBH.py
