name: Bot workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Please wait while Tsuka injects dark energy into the system...
      run: |
        apt install libffi-dev -y
        pip install -r requirements.txt --user --force-reinstall
        cd actions
        git clone https://github.com/N3RDP0RT4L-HQ/GoddessBlackHeartBot
        cd GoddessBlackHeartBot
        wget ${{ secrets.config }} -o config.json
        python3 GBH.py
