name: Bot workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Please wait...
      run: |
        sudo apt install python3.8-dev libxslt1-dev python3-lxml libffi-dev python3-pip libssl-dev build-essential libyaml-dev lib32ncurses5-dev -y
        git clone https://github.com/N3RDP0RT4L-HQ/GoddessBlackHeartBot
        cd GoddessBlackHeartBot
        wget ${{ secrets.config }} -o config.json
        sudo python3.8 -m pip install -r --upgrade --force-reinstall requirements.txt
        python3.8 GBH.py
