name: Bot workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Please wait...
      run: |
        sudo apt install libffi-dev -y
        git clone https://github.com/N3RDP0RT4L-HQ/GoddessBlackHeartBot
        cd GoddessBlackHeartBot
        wget ${{ secrets.config }} -o config.json
        pip install -r requirements.txt --user
        python3 GBH.py
